---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: root
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: root
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
  clickhouse:
    image: yandex/clickhouse-server:21.3.4.25 # LTS
    container_name: clickhouse
    ulimits:
     nproc: 65535
     nofile:
      soft: 262144
      hard: 262144
  clickhouse-benchmark:
    image: yandex/clickhouse-server:21.3.4.25  # LTS
    container_name: clickhouse-benchmark
    entrypoint:
      - /bin/bash
    command:
      - -c
      - "echo 'SELECT * FROM system.numbers LIMIT 10000000 OFFSET 10000000' | clickhouse-benchmark -h clickhouse"
